//Teste de requisição - Categoria

@baseURL = http://localhost:4000

@id = 

###
//GET - Listar as categorias
GET  {{baseURL}}/categorias
Content-Type: application/json
###
//GET - Lista a categorias pelo id
GET  {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
//POST - Incluir uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

 {
        "nome":"Up - 1.0",
        "status": "ativo",
        "foto": {
            "orinalname":"up.png",
            "path": "public/uploads/up.png",
            "size": 45318,
            "mimetype": "image/png"
    }
 }

###
//DELETE - apagar uma categoria
DELETE {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
//PUT - Altera uma categoria
PUT {{baseURL}}/categorias
Content-Type: application/json

{
    "_id": "60b5271627b97e77b58a00aa",
    "nome": "Grupo Econômico",
    "status": "ativo"
}