//Teste de requisição - Categoria

@baseURL = http://localhost:4000

@id = 60b7b5a0ce8a850004f4f2ef

###
//GET - Listar as categorias
GET  {{baseURL}}/categorias
Content-Type: application/json
###
//GET - Lista a categorias pelo id
GET  {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
//POST - Incluir uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

 {
        "nome":"Grupo E - Familia",
        "status": "ativo",
        "foto": {
            "orinalname":"up.png",
            "path": "public/uploads/up.png",
            "size": 45318,
            "mimetype": "image/png"
    }
 }

###
//DELETE - apagar uma categoria
DELETE {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
//PUT - Altera uma categoria
PUT {{baseURL}}/categorias
Content-Type: application/json

{
     "_id": "60b5295c27b97e77b58a00ab",
     "nome":"Grupo E - Familia",
        "status": "ativo",
        "foto": {
            "orinalname":"hyundai.png",
            "path": "public/uploads/hyundai.png",
            "size": 45318,
            "mimetype": "image/png"
    }
}