//Teste de requisição - Categoria

@baseURL = http://localhost:4000

@id = 

###
//GET - Listar as categorias
GET  {{baseURL}}/categorias
Content-Type: application/json
###
//GET - Lista a categorias pelo id
GET  {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
//POST - Incluir uma nova categoria
POST {{baseURL}}/categorias
Content-Type: application/json

{"nome": "Grupo C - SUV", 
"status": "ativo",
"foto": {
    "origianlname": "hyundai.png",
    "path": "public/uploads/hyundai.png",
    "size": 207711,
    "mimetype": "image/png"
}}

###
//DELETE - apagar uma categoria
DELETE {{baseURL}}/categorias/{{id}}
Content-Type: application/json

###
//PUT - Altera uma categoria
PUT {{baseURL}}/categorias
Content-Type: application/json

{
    
}