//Teste de reuisição - Grupos

@baseURL = http://localhost:4000
@id = 
@idCategoria = 60a5968de497473364c123c3

###
// GET - Lista os grupos
GET {{baseURL}}/grupos
Content-Type: application/json

###
//GET - Lista o grupo pelo ID
GET {{baseURL}}/grupos/{{id}}
Content-Type: application/json

###
//GET - Lista o grupo pelo ID da categoria
GET {{baseURL}}/grupos/categoria/{{idCategoria}}
Content-Type: application/json

###
//POST - Incluir um novo grupo
POST {{baseURL}}/grupos
Content-Type: application/json

{
    "nome": "Corolla",
    "status": "ativo",
    "categoria":"60a5968de497473364c123c3",
    "faixaPreco": "luxo",
    "tempoReserva": "3 mês",
    "retirada":{
        "municipio": "Sorocaba",
        "estado": "SP",
        "dataRetirada":"15 de março",
        "horarioRetirada": 10
    }
}

###
//DELETAR um grupo
DELETE {{baseURL}}/grupos/{{id}}
Content-Type: application/json
 
###
//PUT - Altera um grupo
PUT {{baseURL}}/grupos
Content-Type: application/json

{
    
}